package com.local.ducdv.mapper;

import com.local.ducdv.entity.Comment;
import com.local.ducdv.entity.CommentExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	long countByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int deleteByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Delete({ "delete from comments", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Insert({ "insert into comments (id, post_id, ", "content, date)",
			"values (#{id,jdbcType=BIGINT}, #{postId,jdbcType=INTEGER}, ",
			"#{content,jdbcType=VARCHAR}, #{date,jdbcType=TIMESTAMP})" })
	int insert(Comment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int insertSelective(Comment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	List<Comment> selectByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Select({ "select", "id, post_id, content, date", "from comments", "where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.local.ducdv.mapper.CommentMapper.BaseResultMap")
	Comment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") Comment row, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int updateByExample(@Param("row") Comment row, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int updateByPrimaryKeySelective(Comment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Update({ "update comments", "set post_id = #{postId,jdbcType=INTEGER},", "content = #{content,jdbcType=VARCHAR},",
			"date = #{date,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(Comment row);
}