package com.local.ducdv.mapper;

import com.local.ducdv.entity.Post;
import com.local.ducdv.entity.PostExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface PostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	long countByExample(PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int deleteByExample(PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Delete({ "delete from posts", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Insert({ "insert into posts (id, user_id, ", "title, date, content)",
			"values (#{id,jdbcType=BIGINT}, #{userId,jdbcType=INTEGER}, ",
			"#{title,jdbcType=VARCHAR}, #{date,jdbcType=TIMESTAMP}, #{content,jdbcType=LONGVARCHAR})" })
	int insert(Post row);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int insertSelective(Post row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	List<Post> selectByExampleWithBLOBs(PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	List<Post> selectByExample(PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Select({ "select", "id, user_id, title, date, content", "from posts", "where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.local.ducdv.mapper.PostMapper.ResultMapWithBLOBs")
	Post selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") Post row, @Param("example") PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int updateByExampleWithBLOBs(@Param("row") Post row, @Param("example") PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int updateByExample(@Param("row") Post row, @Param("example") PostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	int updateByPrimaryKeySelective(Post row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Update({ "update posts", "set user_id = #{userId,jdbcType=INTEGER},", "title = #{title,jdbcType=VARCHAR},",
			"date = #{date,jdbcType=TIMESTAMP},", "content = #{content,jdbcType=LONGVARCHAR}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKeyWithBLOBs(Post row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posts
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	@Update({ "update posts", "set user_id = #{userId,jdbcType=INTEGER},", "title = #{title,jdbcType=VARCHAR},",
			"date = #{date,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(Post row);

	List<Post> joinPostComment(PostExample example);
}