package com.local.ducdv.entity;

import java.util.Date;

public class Post {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.id
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.user_id
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.title
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.date
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column posts.content
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.id
	 * @return  the value of posts.id
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.id
	 * @param id  the value for posts.id
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.user_id
	 * @return  the value of posts.user_id
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.user_id
	 * @param userId  the value for posts.user_id
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.title
	 * @return  the value of posts.title
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.title
	 * @param title  the value for posts.title
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.date
	 * @return  the value of posts.date
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.date
	 * @param date  the value for posts.date
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column posts.content
	 * @return  the value of posts.content
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column posts.content
	 * @param content  the value for posts.content
	 * @mbg.generated  Thu Feb 23 15:44:42 ICT 2023
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}